tarot_cards = [
    # {"name": "Смерть (Death)", "category": "Старшие Арканы", "meaning": "Трансформация и завершение.", "image_path": "images/death.jpg"},
    # {"name": "Дьявол (The Devil)", "category": "Старшие Арканы", "meaning": "Искушение и материализм.", "image_path": "images/devil.jpg"},
    # {"name": "Десятка Мечей (Ten of Swords)", "category": "Масть Мечей", "meaning": "Предательство и завершение сложного периода.", "image_path": "images/ten-swords.jpg"},
    # {"name": "Тройка Кубков (Three of Cups)", "category": "Масть Кубков", "meaning": "Празднование и дружба.", "image_path": "images/three-cups.jpg"},
    # {"name": "Башня (The Tower)", "category": "Старшие Арканы", "meaning": "Потрясение и внезапные перемены.", "image_path": "images/tower.jpg"},
    # {"name": "Туз Пентаклей (Ace of Pentacles)", "category": "Масть Пентаклей", "meaning": "Новые финансовые возможности и стабильность.", "image_path": "images/ace-pentacles.jpg"},
    # {"name": "Иерофант (The Hierophant)", "category": "Старшие Арканы", "meaning": "Традиции, духовность и наставничество.", "image_path": "images/hierophant.jpg"},
    # {"name": "Влюблённые (The Lovers)", "category": "Старшие Арканы", "meaning": "Гармония, романтические отношения и союз.", "image_path": "images/love.jpg"},
    # {"name": "Мир (The World)", "category": "Старшие Арканы", "meaning": "Завершение, целостность и достижение цели.", "image_path": "images/peace.jpg"},
    # {"name": "Звезда (The Star)", "category": "Старшие Арканы", "meaning": "Надежда, вдохновение и исполнение желаний.", "image_path": "images/star.jpg"},
    # {"name": "Луна (The Moon)", "category": "Старшие Арканы", "meaning": "Иллюзии, интуиция и скрытые страхи.", "image_path": "images/moon.jpg"},
    # {"name": "Туз Мечей (Ace of Swords)", "category": "Масть Мечей", "meaning": "Ясность, истина и интеллектуальный прорыв.", "image_path": "images/ace-of-swords.jpg"},
    # {"name": "Отшельник (The Hermit)", "category": "Старшие Арканы", "meaning": "Поиск истины, уединение и внутренняя мудрость.", "image_path": "images/hermit.jpg"},
    # {"name": "Пятёрка Мечей (Five of Swords – Defeat)", "category": "Масть Мечей", "meaning": "Потери, конфликт и разочарование.", "image_path": "images/defeat.jpg"},
    # {"name": "Восьмёрка Пентаклей (Eight of Pentacles – Material Work)", "category": "Масть Пентаклей", "meaning": "Усердная работа, мастерство и прогресс.", "image_path": "images/material-work.jpg"},
    # {"name": "Восьмёрка Жезлов (Eight of Wands – Swiftness)", "category": "Масть Жезлов", "meaning": "Стремительное развитие событий, энергия и движение вперёд.", "image_path": "images/swiftness.jpg"},
    # {"name": "Король Пентаклей (King of Pentacles)", "category": "Масть Пентаклей", "meaning": "Материальный успех, надёжность и лидерство в финансах.", "image_path": "images/king-of-pentacles.jpg"},
    # {"name": "Колесо Фортуны (Wheel of Fortune)", "category": "Старшие Арканы", "meaning": "Судьба, перемены и цикличность жизни.", "image_path": "images/wheel-of-fortune.jpg"},
    # {"name": "Справедливость (Justice)", "category": "Старшие Арканы", "meaning": "Честность, ответственность и кармический баланс.", "image_path": "images/justice.jpg"},
    # {"name": "Сила (Strength)", "category": "Старшие Арканы", "meaning": "Мужество, внутренний контроль и стойкость.", "image_path": "images/strength.jpg"},
    # {"name": "Восьмёрка Кубков (Eight of Cups – Abandoned Success)", "category": "Масть Кубков", "meaning": "Отказ от прошлого, поиск нового пути.", "image_path": "images/abandoned-success.jpg"},
    # {"name": "Колесница (The Chariot)", "category": "Старшие Арканы", "meaning": "Победа через силу воли и контроль.", "image_path": "images/chariot.jpg"},
    # {"name": "Император (The Emperor)", "category": "Старшие Арканы", "meaning": "Стабильность, структура и авторитет.", "image_path": "images/emperor.jpg"},
    # {"name": "Шут (The Fool)", "category": "Старшие Арканы", "meaning": "Начало пути, свобода и приключения.", "image_path": "images/fool.jpg"},
    # {"name": "Повешенный (The Hanged Man)", "category": "Старшие Арканы", "meaning": "Жертва, переосмысление и перспектива.", "image_path": "images/hanged-man.jpg"},
    # {"name": "Королева Мечей (Queen of Swords)", "category": "Масть Мечей", "meaning": "Интеллект, независимость и ясность мысли.", "image_path": "images/queen-of-swords.jpg"},
    # {"name": "Солнце (The Sun)", "category": "Старшие Арканы", "meaning": "Радость, успех и просветление.", "image_path": "images/sun.jpg"},
    {"name": "Верховная Жрица (The High Priestess)", "category": "Старшие Арканы", "meaning": "Интуиция, тайное знание и духовная сила.", "image_path": "images/high-priestess.jpg"},
    {"name": "Король Жезлов (King of Wands)", "category": "Масть Жезлов", "meaning": "Амбиции, лидерство и страсть к делу.", "image_path": "images/king-of-wands.jpg"},
    {"name": "Рыцарь Кубков (Knight of Cups)", "category": "Масть Кубков", "meaning": "Романтический посланник, эмоциональные предложения.", "image_path": "images/knight-of-cups.jpg"},
    {"name": "Девятка Кубков (Nine of Cups – Material Happiness)", "category": "Масть Кубков", "meaning": "Изобилие, комфорт и удовлетворение от достигнутого.", "image_path": "images/material-happiness.jpg"},
    {"name": "Шестёрка Кубков (Six of Cups – Pleasure)", "category": "Масть Кубков", "meaning": "Наслаждение жизнью, удовлетворение и счастье.", "image_path": "images/pleasure.jpg"},
    {"name": "Королева Пентаклей (Queen of Pentacles)", "category": "Масть Пентаклей", "meaning": "Забота, щедрость и уверенность в материальном мире.", "image_path": "images/queen-of-pentacles.jpg"},
]
