tarot_cards = [
    # {"name": "Смерть", "meaning": "Трансформация и завершение.", "image_path": "images/death.jpg"},
    # {"name": "Дьявол", "meaning": "Искушение и материализм.", "image_path": "images/devil.jpg"},
    # {"name": "10 мечей", "meaning": "Предательство и завершение сложного периода.", "image_path": "images/ten-swords.jpg"},
    # {"name": "Три чаши", "meaning": "Празднование и дружба.", "image_path": "images/three-cups.jpg"},
    # {"name": "Башня", "meaning": "Потрясение и внезапные перемены.", "image_path": "images/tower.jpg"},
    # {"name": "Туз пентаклей", "meaning": "Новые финансовые возможности и стабильность.", "image_path": "images/ace-pentacles.jpg"},
    # {"name": "Иерофант", "meaning": "Традиции, духовность и наставничество.", "image_path": "images/hierophant.jpg"},
    # {"name": "Любовь", "meaning": "Гармония, романтические отношения и союз.", "image_path": "images/love.jpg"},
    # {"name": "Мир", "meaning": "Спокойствие, завершение и целостность.", "image_path": "images/peace.jpg"},
    # {"name": "Звезда", "meaning": "Надежда, вдохновение и исполнение желаний.", "image_path": "images/star.jpg"},
    {"name": "Луна", "meaning": "Иллюзии, интуиция и скрытые страхи.", "image_path": "images/moon.jpg"},
    {"name": "Туз мечей", "meaning": "Ясность, истина и интеллектуальный прорыв.", "image_path": "images/ace-of-swords.jpg"},
    {"name": "Отшельник", "meaning": "Поиск истины, уединение и внутренняя мудрость.", "image_path": "images/hermit.jpg"},
    {"name": "Поражение", "meaning": "Потери, конфликт и разочарование.", "image_path": "images/defeat.jpg"},
    {"name": "Материальный труд", "meaning": "Усердная работа, мастерство и прогресс.", "image_path": "images/material-work.jpg"},
    {"name": "Быстрота", "meaning": "Стремительное развитие событий, энергия и движение вперёд.", "image_path": "images/swiftness.jpg"},
    {"name": "Король пентаклей", "meaning": "Материальный успех, надёжность и лидерство в финансах.", "image_path": "images/king-of-pentacles.jpg"},
    {"name": "Колесо фортуны", "meaning": "Судьба, перемены и цикличность жизни.", "image_path": "images/wheel-of-fortune.jpg"},
    {"name": "Справедливость", "meaning": "Честность, ответственность и кармический баланс.", "image_path": "images/justice.jpg"},
    {"name": "Сила", "meaning": "Мужество, внутренний контроль и стойкость.", "image_path": "images/strength.jpg"},
]
