tarot_cards = [
    {
        "name": "Смерть (Death)",
        "category": "Старшие Арканы",
        "meaning": "Трансформация и завершение.",
        "image_path": "images/death.jpg",
    },
    {
        "name": "Дьявол (The Devil)",
        "category": "Старшие Арканы",
        "meaning": "Искушение и материализм.",
        "image_path": "images/devil.jpg",
    },
    {
        "name": "Десятка Мечей (Ten of Swords)",
        "category": "Масть Мечей",
        "meaning": "Предательство и завершение сложного периода.",
        "image_path": "images/ten-swords.jpg",
    },
    {
        "name": "Тройка Кубков (Three of Cups)",
        "category": "Масть Кубков",
        "meaning": "Празднование и дружба.",
        "image_path": "images/three-cups.jpg",
    },
    {
        "name": "Башня (The Tower)",
        "category": "Старшие Арканы",
        "meaning": "Потрясение и внезапные перемены.",
        "image_path": "images/tower.jpg",
    },
    {
        "name": "Туз Пентаклей (Ace of Pentacles)",
        "category": "Масть Пентаклей",
        "meaning": "Новые финансовые возможности и стабильность.",
        "image_path": "images/ace-pentacles.jpg",
    },
    {
        "name": "Иерофант (The Hierophant)",
        "category": "Старшие Арканы",
        "meaning": "Традиции, духовность и наставничество.",
        "image_path": "images/hierophant.jpg",
    },
    {
        "name": "Двойка Кубков (Two of Cups – Love)",
        "category": "Масть Кубков",
        "meaning": "Партнёрство, союз, взаимная привязанность и гармония в отношениях.",
        "image_path": "images/love.jpg",
    },
    {
        "name": "Влюблённые (The Lovers)",
        "category": "Старшие Арканы",
        "meaning": "Гармония, романтические отношения и союз.",
        "image_path": "images/lovers.jpg",
    },
    {
        "name": "Мир (The World)",
        "category": "Старшие Арканы",
        "meaning": "Завершение, целостность и достижение цели.",
        "image_path": "images/world.jpg",
    },
    {
        "name": "Звезда (The Star)",
        "category": "Старшие Арканы",
        "meaning": "Надежда, вдохновение и исполнение желаний.",
        "image_path": "images/star.jpg",
    },
    {
        "name": "Луна (The Moon)",
        "category": "Старшие Арканы",
        "meaning": "Иллюзии, интуиция и скрытые страхи.",
        "image_path": "images/moon.jpg",
    },
    {
        "name": "Туз Мечей (Ace of Swords)",
        "category": "Масть Мечей",
        "meaning": "Ясность, истина и интеллектуальный прорыв.",
        "image_path": "images/ace-of-swords.jpg",
    },
    {
        "name": "Отшельник (The Hermit)",
        "category": "Старшие Арканы",
        "meaning": "Поиск истины, уединение и внутренняя мудрость.",
        "image_path": "images/hermit.jpg",
    },
    {
        "name": "Пятёрка Мечей (Five of Swords – Defeat)",
        "category": "Масть Мечей",
        "meaning": "Потери, конфликт и разочарование.",
        "image_path": "images/defeat.jpg",
    },
    {
        "name": "Восьмёрка Пентаклей (Eight of Pentacles – Material Work)",
        "category": "Масть Пентаклей",
        "meaning": "Усердная работа, мастерство и прогресс.",
        "image_path": "images/material-work.jpg",
    },
    {
        "name": "Восьмёрка Жезлов (Eight of Wands – Swiftness)",
        "category": "Масть Жезлов",
        "meaning": "Стремительное развитие событий, энергия и движение вперёд.",
        "image_path": "images/swiftness.jpg",
    },
    {
        "name": "Король Пентаклей (King of Pentacles)",
        "category": "Масть Пентаклей",
        "meaning": "Материальный успех, надёжность и лидерство в финансах.",
        "image_path": "images/king-of-pentacles.jpg",
    },
    {
        "name": "Колесо Фортуны (Wheel of Fortune)",
        "category": "Старшие Арканы",
        "meaning": "Судьба, перемены и цикличность жизни.",
        "image_path": "images/wheel-of-fortune.jpg",
    },
    {
        "name": "Справедливость (Justice)",
        "category": "Старшие Арканы",
        "meaning": "Честность, ответственность и кармический баланс.",
        "image_path": "images/justice.jpg",
    },
    {
        "name": "Сила (Strength)",
        "category": "Старшие Арканы",
        "meaning": "Мужество, внутренний контроль и стойкость.",
        "image_path": "images/strength.jpg",
    },
    {
        "name": "Восьмёрка Кубков (Eight of Cups – Abandoned Success)",
        "category": "Масть Кубков",
        "meaning": "Отказ от прошлого, поиск нового пути.",
        "image_path": "images/abandoned-success.jpg",
    },
    {
        "name": "Колесница (The Chariot)",
        "category": "Старшие Арканы",
        "meaning": "Победа через силу воли и контроль.",
        "image_path": "images/chariot.jpg",
    },
    {
        "name": "Император (The Emperor)",
        "category": "Старшие Арканы",
        "meaning": "Стабильность, структура и авторитет.",
        "image_path": "images/emperor.jpg",
    },
    {
        "name": "Шут (The Fool)",
        "category": "Старшие Арканы",
        "meaning": "Начало пути, свобода и приключения.",
        "image_path": "images/fool.jpg",
    },
    {
        "name": "Повешенный (The Hanged Man)",
        "category": "Старшие Арканы",
        "meaning": "Жертва, переосмысление и перспектива.",
        "image_path": "images/hanged-man.jpg",
    },
    {
        "name": "Королева Мечей (Queen of Swords)",
        "category": "Масть Мечей",
        "meaning": "Интеллект, независимость и ясность мысли.",
        "image_path": "images/queen-of-swords.jpg",
    },
    {
        "name": "Солнце (The Sun)",
        "category": "Старшие Арканы",
        "meaning": "Радость, успех и просветление.",
        "image_path": "images/sun.jpg",
    },
    {
        "name": "Верховная Жрица (The High Priestess)",
        "category": "Старшие Арканы",
        "meaning": "Интуиция, тайное знание и духовная сила.",
        "image_path": "images/high-priestess.jpg",
    },
    {
        "name": "Король Жезлов (King of Wands)",
        "category": "Масть Жезлов",
        "meaning": "Амбиции, лидерство и страсть к делу.",
        "image_path": "images/king-of-wands.jpg",
    },
    {
        "name": "Рыцарь Кубков (Knight of Cups)",
        "category": "Масть Кубков",
        "meaning": "Романтический посланник, эмоциональные предложения.",
        "image_path": "images/knight-of-cups.jpg",
    },
    {
        "name": "Девятка Кубков (Nine of Cups – Material Happiness)",
        "category": "Масть Кубков",
        "meaning": "Изобилие, комфорт и удовлетворение от достигнутого.",
        "image_path": "images/material-happiness.jpg",
    },
    {
        "name": "Шестёрка Кубков (Six of Cups – Pleasure)",
        "category": "Масть Кубков",
        "meaning": "Наслаждение жизнью, удовлетворение и счастье.",
        "image_path": "images/pleasure.jpg",
    },
    {
        "name": "Королева Пентаклей (Queen of Pentacles)",
        "category": "Масть Пентаклей",
        "meaning": "Забота, щедрость и уверенность в материальном мире.",
        "image_path": "images/queen-of-pentacles.jpg",
    },
    {
        "name": "Покой (Peace – Двойка Мечей)",
        "category": "Масть Мечей",
        "meaning": "Внутренний баланс и тишина после конфликта. Символизирует необходимость сделать выбор, сохраняя спокойствие и доверяя интуиции, а не внешним обстоятельствам.",
        "image_path": "images/peace.jpg",
    },
    {
        "name": "Туз Жезлов (Ace of Wands)",
        "category": "Масть Жезлов",
        "meaning": "Новые начинания, вдохновение и энергия.",
        "image_path": "images/ace-of-wands.jpg",
    },
    {
        "name": "Изобилие (Abundance)",
        "category": "Старшие Арканы",
        "meaning": "Изобилие, процветание и излишек.",
        "image_path": "images/abundance.jpg",
    },
    {
        "name": "Императрица (The Empress)",
        "category": "Старшие Арканы",
        "meaning": "Материнство, забота и плодородие.",
        "image_path": "images/empress.jpg",
    },
    {
        "name": "Иллюзорный успех (Illusionary Success)",
        "category": "Масть Кубков",
        "meaning": "Обманчивые успехи и временное удовлетворение.",
        "image_path": "images/illusionary-success.jpg",
    },
    {
        "name": "Потери в удовольствии (Loss in Pleasure)",
        "category": "Масть Кубков",
        "meaning": "Разочарования и потеря радости.",
        "image_path": "images/loss-in-pleasure.jpg",
    },
    {
        "name": "Маг (The Magician)",
        "category": "Старшие Арканы",
        "meaning": "Мастерство, ресурсы и реализация возможностей.",
        "image_path": "images/magician.jpg",
    },
    {
        "name": "Укороченная сила (Shortened Force)",
        "category": "Старшие Арканы",
        "meaning": "Недостаток силы, усталость и потеря энергии.",
        "image_path": "images/shortened-force.jpg",
    },
    {
        "name": "Тоска (Sorrow)",
        "category": "Масть Мечей",
        "meaning": "Печаль, разочарование и утраты.",
        "image_path": "images/sorrow.jpg",
    },
    {
        "name": "Двойка Жезлов (Two of Wands – Dominion)",
        "category": "Масть Жезлов",
        "meaning": "Планирование будущего, амбиции и власть над обстоятельствами.",
        "image_path": "images/dominion.jpg",
    },
    {
        "name": "Суд (Judgement)",
        "category": "Старшие Арканы",
        "meaning": "Пробуждение, возрождение и важные решения.",
        "image_path": "images/judgement.jpg",
    },
    {
        "name": "Король Мечей (King of Swords)",
        "category": "Масть Мечей",
        "meaning": "Интеллект, справедливость и лидерство через разум.",
        "image_path": "images/king-of-swords.jpg",
    },
    {
        "name": "Рыцарь Пентаклей (Knight of Pentacles)",
        "category": "Масть Пентаклей",
        "meaning": "Упорный труд, надёжность и стремление к цели.",
        "image_path": "images/knight-of-pentacles.jpg",
    },
    {
        "name": "Королева Жезлов (Queen of Wands)",
        "category": "Масть Жезлов",
        "meaning": "Уверенность, харизма и внутренняя сила.",
        "image_path": "images/queen-of-wands.jpg",
    },
    {
        "name": "Четвёрка Мечей (Four of Swords – Rest from Strife)",
        "category": "Масть Мечей",
        "meaning": "Восстановление, медитация и временный отдых после трудностей.",
        "image_path": "images/rest-from-strife.jpg",
    },
    {
        "name": "Пятёрка Пентаклей (Five of Pentacles – Material Trouble)",
        "category": "Масть Пентаклей",
        "meaning": "Бедность, потери и чувство изоляции или нехватки.",
        "image_path": "images/material-trouble.jpg",
    },
    {
        "name": "Четвёрка Жезлов (Four of Wands – Perfected Work)",
        "category": "Масть Жезлов",
        "meaning": "Празднование, завершение, гармония и стабильность в доме.",
        "image_path": "images/perfected-work.jpg",
    },
    {
        "name": "Шестёрка Мечей (Six of Swords – Earned Success)",
        "category": "Масть Мечей",
        "meaning": "Переход через трудности, движение к лучшему, путь к внутреннему покою.",
        "image_path": "images/earned-success.jpg",
    },
    {
        "name": "Десятка Пентаклей (Ten of Pentacles – Wealth)",
        "category": "Масть Пентаклей",
        "meaning": "Богатство, семейные традиции и материальное изобилие.",
        "image_path": "images/wealth.jpg",
    },
    {
        "name": "Десятка Жезлов (Ten of Wands – Oppression)",
        "category": "Масть Жезлов",
        "meaning": "Крайнее истощение, завершение болезненного цикла.",
        "image_path": "images/oppression.jpg",
    },
    {
        "name": "Семёрка Мечей (Seven of Swords – Unstable Effort)",
        "category": "Масть Мечей",
        "meaning": "Хитрость, нестабильность, уход от ответственности.",
        "image_path": "images/unstable-effort.jpg",
    },
    {
        "name": "Рыцарь Жезлов (Knight of Wands)",
        "category": "Масть Жезлов",
        "meaning": "Дерзость, страсть и стремительное движение вперёд.",
        "image_path": "images/knight-of-wands.jpg",
    },
    {
        "name": "Рыцарь Мечей (Knight of Swords)",
        "category": "Масть Мечей",
        "meaning": "Решительность, интеллектуальный порыв и стремление к действию.",
        "image_path": "images/knight-of-swords.jpg",
    },
    {
        "name": "Шестёрка Пентаклей (Six of Pentacles – Material Success)",
        "category": "Масть Пентаклей",
        "meaning": "Щедрость, баланс между отдачей и получением.",
        "image_path": "images/material-success.jpg",
    },
    {
        "name": "Тройка Жезлов (Three of Wands – Established Strength)",
        "category": "Масть Жезлов",
        "meaning": "Настойчивость и сила воли в преодолении трудностей.",
        "image_path": "images/established-strength.jpg",
    },
    {
        "name": "Девятка Жезлов (Nine of Wands – Great Strength)",
        "category": "Масть Жезлов",
        "meaning": "Устойчивость, стойкость и последняя защита своих позиций.",
        "image_path": "images/great-strength.jpg",
    },
    {
        "name": "Двойка Пентаклей (Two of Pentacles – Harmonious Change)",
        "category": "Масть Пентаклей",
        "meaning": "Баланс и адаптация в изменяющихся обстоятельствах.",
        "image_path": "images/harmonious-change.jpg",
    },
    {
        "name": "Пятёрка Жезлов (Five of Wands – Strife)",
        "category": "Масть Жезлов",
        "meaning": "Конфликты и соперничество, ведущие к росту.",
        "image_path": "images/strife.jpg",
    },
    {
        "name": "Умеренность (Temperance)",
        "category": "Старшие Арканы",
        "meaning": "Гармония, умеренность и целеустремлённость.",
        "image_path": "images/temperance.jpg",
    },
    {
        "name": "Семёрка Жезлов (Seven of Wands – Valour)",
        "category": "Масть Жезлов",
        "meaning": "Смелость и защита своих позиций.",
        "image_path": "images/valour.jpg",
    },
    {
        "name": "Шестёрка Жезлов (Six of Wands – Victory)",
        "category": "Масть Жезлов",
        "meaning": "Победа, признание и успех после усилий.",
        "image_path": "images/victory.jpg",
    },
    {
        "name": "Четвёрка Пентаклей (Four of Pentacles)",
        "category": "Масть Пентаклей",
        "meaning": "Контроль, стабильность, безопасность и обладание. Карта символизирует как защиту ресурсов, так и страх потери, который может привести к чрезмерному контролю.",
        "image_path": "images/earthing-power.jpg",
    },
    {
        "name": "Четвёрка Кубков (Four of Cups – Blended Pleasure)",
        "category": "Масть Кубков",
        "meaning": "Эмоциональное недовольство, необходимость переоценки желаний.",
        "image_path": "images/blended-pleasure.jpg",
    },
    {
        "name": "Девятка Мечей (Nine of Swords – Despair and Cruelty)",
        "category": "Масть Мечей",
        "meaning": "Беспокойство, угрызения совести и внутренние страдания.",
        "image_path": "images/despair-and-cruelty.jpg",
    },
    {
        "name": "Король Кубков (King of Cups)",
        "category": "Масть Кубков",
        "meaning": "Эмоциональная зрелость, сочувствие и контроль над чувствами.",
        "image_path": "images/king-of-cups.jpg",
    },
    {
        "name": "Десятка Кубков (Ten of Cups – Perfected Success)",
        "category": "Масть Кубков",
        "meaning": "Эмоциональное удовлетворение, семейное счастье и гармония.",
        "image_path": "images/perfect-success.jpg",
    },
    {
        "name": "Принцесса Кубков (Princess of Cups)",
        "category": "Масть Кубков",
        "meaning": "Творческое вдохновение, интуиция и чувствительность.",
        "image_path": "images/princess-of-cups.jpg",
    },
    {
        "name": "Принцесса Мечей (Princess of Swords)",
        "category": "Масть Мечей",
        "meaning": "Интеллектуальное любопытство, наблюдательность и стремление к истине.",
        "image_path": "images/princess-of-swords.jpg",
    },
    {
        "name": "Принцесса Жезлов (Princess of Wands)",
        "category": "Масть Жезлов",
        "meaning": "Энергия новых начинаний, креативность и страсть к самовыражению.",
        "image_path": "images/princess-of-wands.jpg",
    },
    {
        "name": "Королева Кубков (Queen of Cups)",
        "category": "Масть Кубков",
        "meaning": "Сострадание, глубокая эмоциональность и развитая интуиция.",
        "image_path": "images/queen-of-cups.jpg",
    },
    {
        "name": "Принцесса Пентаклей (Princess of Pentacles)",
        "category": "Масть Пентаклей",
        "meaning": "Практичность, стремление к знаниям и уверенные шаги к материальной стабильности.",
        "image_path": "images/princess-of-pentacles.jpg",
    },
    {
        "name": "Туз Кубков (Ace of Cups)",
        "category": "Масть Кубков",
        "meaning": "Начало новых чувств, любовь, вдохновение и духовное обновление.",
        "image_path": "images/ace-of-cups.jpg",
    },
    {
        "name": "Четвёрка Пентаклей (Four of Pentacles – Perfect Work)",
        "category": "Масть Пентаклей",
        "meaning": "Стабильность, упорный труд, достижение надёжного фундамента и мастерство в деле.",
        "image_path": "images/perfect-work.jpg",
    },
    {
        "name": "Семёрка Пентаклей (Seven of Pentacles - Success Unfulfilled)",
        "category": "Масть Пентаклей",
        "meaning": "Оценка прогресса, размышление над результатами и период ожидания. Карта указывает на вложенный труд, но может сигнализировать о задержках или неудовлетворённости текущими достижениями.",
        "image_path": "images/success-unfulfilled.jpg",
    },
]
